header:
  license:
    spdx-id: LGPL-2.0-or-later

  paths-ignore:
    - '.gitignore'
    - 'lib/xsom'
    - 'dist'
    - '**/.idea'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'LICENSE.uri-libs.txt'

  comment: on-failure